# Cloudflare Workers configuration
name = "vanced-chatbot"
main = "src/worker.js"
compatibility_date = "2024-01-15"

# Environment variables
[env.production.vars]
# Thêm các environment variables vào Cloudflare Dashboard > Workers > Settings > Environment Variables:
# APPS_SCRIPT_URL = https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec

# Development environment
[env.development]
vars = { }

# Default environment (for --env="")
[vars]

# Build configuration
[build]
command = ""

# Routes (nếu cần custom domain)
# routes = [
#   { pattern = "chat.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# Durable Objects configuration - WebSocket Chat System
[[durable_objects.bindings]]
name = "WEBSOCKET_CHAT_ROOM"
class_name = "WebSocketChatRoom"

# Durable Objects migrations (SQLite for Free Plan)
[[migrations]]
tag = "v1"
new_sqlite_classes = ["P2PSignalingRoom"]

[[migrations]]
tag = "v2"
renamed_classes = [
  { from = "P2PSignalingRoom", to = "WebSocketChatRoom" }
]

# KV namespaces (cho future chat history storage)
# kv_namespaces = [
#   { binding = "CHAT_HISTORY", id = "8fb44eea85a94f6b8e5e5a6b5b402f12", preview_id = "your-preview-kv-namespace-id" }
# ]

# Compatibility flags
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true