# Cloudflare Workers configuration
name = "vanced-support-chatbot"
main = "New_worker.js"
compatibility_date = "2024-01-15"

# Environment variables
[env.production.vars]
# Thêm các environment variables vào Cloudflare Dashboard > Workers > Settings > Environment Variables:
# OPENROUTER_API_KEY = your-openrouter-api-key
# APPS_SCRIPT_URL = https://script.google.com/macros/s/YOUR_SCRIPT_ID/exec

# Development environment
[env.development]
vars = { }

# Build configuration
[build]
command = ""

# Routes (nếu cần custom domain)
# routes = [
#   { pattern = "chat.yourdomain.com/*", zone_name = "yourdomain.com" }
# ]

# KV namespaces (cho future chat history storage)
# kv_namespaces = [
#   { binding = "CHAT_HISTORY", id = "your-kv-namespace-id", preview_id = "your-preview-kv-namespace-id" }
# ]

# Compatibility flags
compatibility_flags = ["nodejs_compat"]